main: com.blackoutburst.workshop.Main
name: Workshop
version: 2.1.0
api-version: 1.13
author: Blackoutburst & Skye
description: Party Game Workshop Practice
depend: [ViaVersion]
commands:
  play:
    description: Start the game
    usage: /play
  l:
    description: End the game
    usage: /l
  scanwand:
    permission: workshop.admin
    description: Give the scanwand
    usage: /scanwand
  logicscan:
    permission: workshop.admin
    description: Make a logic scan
    usage: /logicscan
  decoscan:
    permission: workshop.admin
    description: Make a deco scan
    usage: /decoscan
  pastemap:
    permission: workshop.admin
    description: Paste a map
    usage: /pastemap
  setspawn:
    permission: workshop.admin
    description: Set the spawn
    usage: /setspawn
  recipeadd:
    permission: workshop.admin
    description: Add a new craft
    usage: /recipeadd
  spawn:
    description: Go to spawn
    usage: /spawn
  setcraftlimit:
    description: Set how much craft you need to do
    usage: /setcraftlimit
  setcraftamount:
    description: Set how much craft you need to do
    usage: /setcraftamount
  setunlimitedcraft:
    description: Toggle craft requirement
    usage: /setunlimitedcraft
  rngtype:
      description: Changes randomisation type
      usage: /rngtype
  reloadmaps:
    permission: workshop.admin
    description: Reloads in-memory copy of maps
    usage: /reloadmaps
  settimelimit:
    description: Sets the time limit, for timed gameplay
    usage: /settimelimit
  setcountdown:
    description: Sets the countdown length at the start of games
    usage: /setcountdown
  listmaps:
    description: list maps
    usage: /listmaps
  deletemap:
    permission: workshop.admin
    description: Delete a map
    usage: /deletemap
  shownonpbs:
    description: Enables/disables showing difference to PB for non-PBing games
    usage: /shownonpbs
  editmap:
    description: Allows you to edit the data of a map
    usage: /editmap

  permissions:
    workshop.admin:
      default: op